### ISSUE TITLE
Added contentview for MQTT messages

### ISSUE THREAD

**Issue by abbbe** [nikitastupin/mitmproxy-mqtt-script#2]
I have added a contentview code for MQTT messages, heavily based on the code from your repo.
Here is a link to pull request (not merged yet): https://github.com/mitmproxy/mitmproxy/pull/5588.
Just FYI, because it seems to be a part of your roadmap ).

**Comment by nikitastupin** [comment]
Thanks @abbbe! Slowly but steadily we're moving along the roadmap 😉
